# 24.5 Data Encoding

1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding

## 24.5.1 Nominal/OHE Encoding

- One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithm.
- In this technique, each category is represented as a binary vector where each bit corresponds to a unique cartegory. 
- For example, if we have a catgorical variable "color" with three possible values (red, green, blue), we can represent it as one hot encoding as follows:

1. Red: [1,0,0]
2. Green: [0,1,0]
3. Blue: [0,0,1]

Here in One Hot Encoding, the catrgories are converted in numerical values like this: 
OHE: Red  Green  Blue
     
     1    0     0
     
     0    1     0
     
     0    0     1

- This is like converting every different catgorical data into a feature.

Another Example we can see is: Suppose we have given 2 features(Experience, Degree) and we have to predict the salary of the employee.
- Now here experience is a numerical value, but degree(BE, Phd, Masters, etc) is a categorical value and the model does not understand the categorical values.
- For a Human, Degrees like BE, Phd, Masters, etc have different values, but for models they are just categories.
- Model only understand numerical values. Therefore, we try to convert these categorical features into some meaningful numerical value.
- This process is basically called as Data Encoding.

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
# Creating a simple datafarme
df = pd.DataFrame({
    'color' : ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [5]:
# Creating an instance of OneHotEncoder
encoder = OneHotEncoder()

In [6]:
## Perform fit and transform
encoded_value = encoder.fit_transform(df[['color']]).toarray()

In [7]:
encoded_df = pd.DataFrame(encoded_value, columns = encoder.get_feature_names_out())

In [8]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [9]:
# When every you are getting new data:
encoder.transform([['blue']]).toarray()

c:\Users\OM MAKWANA\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [10]:
pd.concat([df, encoded_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

So there are some disadvantages of OHE:
- Suppose, in a feature we have 100(different) categorical values...So is we try to encode this feature, there will be another 100 new features. So if we have many many categories we should avoid OHE.
- Another dis-adv is about Sparse Matrix. 

Sparse Matrix:  If we have n categories in a feature, and if we try to convert this into OHE, we will get n different columns. And in every column we will have ones and zeros, these ones and zeros is Sparse Matrix.

- And when there is a sparse matrix, it usually leads to something calles as overfitting.(Overfitting is a machine learning error that occurs when a model is too closely tuned to training data. This can result in the model making accurate predictions for the training data, but poor predictions for new data.)

## 24.5.2.1 Label Encoding

- Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data. 
- Label encoding involves assiging a unique numerical label to each category in the variable. 
- The Labels are usually assigned in alphabetical order or based on the frequency of the category.
- For eg. if we have a categorical variable "color" with three possible values(Red, Green, Blue), we can represent it using label encoding as follows:

1. Red: 1
2. Green: 2
3. Blue: 3

In [11]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
lbl_encoder = LabelEncoder()

In [14]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\OM MAKWANA\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [15]:
lbl_encoder.transform([['red']])
# Similarly for other entries.

c:\Users\OM MAKWANA\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

### There's one dis-adv of label encoder:
- Whenever the unique value is assigned to a category, this unique labels start from zero and so on...and its like 0 < 1 < 2. Since red is assigned '2' my model may consider that red is greater than blue and green, as its assign value 2. 
- Green is assigned the value 1, then my model will start thinking that because the numerical value is higher.
- And in any machine learning algorithm, whne we use numerical values for the calculation. So the model will think that green may be greater than blue, it may be less than red.
- These are nominal values, we dont assign them a rank. If we had a usecase where we specifically need to assign ranks for that we can use something called as ordinal encoding.

## 24.5.2.2 Ordinal Encoding

- It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order.
- For example, if we have a categorical variable "education level" with four possible values (high school, college, graduate, post-graduate), we can represent it using ordinal encoding as follows:

1. high school: 1 
2. college: 2
3. graduate: 3 
4. post-graduate: 4

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
# Creating a simple dataframe
df = pd.DataFrame({
    'size': ['small','medium','large','medium','small','large']
})

In [21]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [23]:
# Creating an instance for OrdinalEncoder and then fit_transform
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [24]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [26]:
encoder.transform([['small']])

c:\Users\OM MAKWANA\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])