# Section 24: Feature Engineering

## 24.1 Handling Missing Values

- Its important to understanf that, whenever you are trying to solve a data science project or it can be a deep learning project or machine learning project, the first thing required is specifically data. 
- In the real world scenario, when you working for companies and all, you will be getting a lot of messey data. The raw data would have a lot of missing values.

### Missing Values
Missing values occurs in dataset when some of the information is not stored for a variable.

There are three mechanisms:

### 1. Missing Completely at Random, MCAR:
Missing completely at random (MCAR) is a type of missing data mechanism in which the probability of a value being missing is unrelated to both the observed data and the missing data. In other words, if the data is MCAR, the missing values are randomly distributed throughout the dataset, and there is no systematic reason for why they are missing.

For example, in a survey about the prevalence of a certain disease, the missing data might be MCAR if the survey participants with missing values for certain questions were selected randomly and their missing responses are not related to their disease status or any other variables measured in the survey.

### 2. Missing at Random MAR:
Missing at Random (MAR) is a type of missing data mechanism in which the probability of a value being missing depends only on the observed data, but not on the missing data itself. In other words, if the data is MAR, the missing values are systematically related to the observed data, but not to the missing data.
Here are a few examples of missing at random:

Income data: Suppose you are collecting income data from a group of people, but some participants choose not to report their income. If the decision to report or not report income is related to the participant's age or gender, but not to their income level, then the data is missing at random.

Medical data: Suppose you are collecting medical data on patients, including their blood pressure, but some patients do not report their blood pressure. If the patients who do not report their blood pressure are more likely to be younger or have healthier lifestyles, but the missingness is not related to their actual blood pressure values, then the data is missing at random.

## 3. Missing data not at random (MNAR) 
It is a type of missing data mechanism where the probability of missing values depends on the value of the missing data itself. In other words, if the data is MNAR, the missingness is not random and is dependent on unobserved or unmeasured factors that are associated with the missing values.

For example, suppose you are collecting data on the income and job satisfaction of employees in a company. If employees who are less satisfied with their jobs are more likely to refuse to report their income, then the data is not missing at random. In this case, the missingness is dependent on job satisfaction, which is not directly observed or measured.

In [1]:
import seaborn as sns
import numpy as np
import pandas as pd

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
# To Check missing values:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
## Easiest way to handle missing values: Delete the rows or data points to handle missing values😂😂.

## But its not appropriate if there are lots of missing values in the dataset.

## We can also drop the columns with missing values, but what if its an important column for our project...??
 
## Code for dropping columns with missing values:  df.dropna(axis = 1)
df.shape

(891, 15)

### Imputation of Missing Values

1. Mean Value Imputation

In [6]:
df['Age_Mean'] = df['age'].fillna(df['age'].mean())

In [7]:
df[['Age_Mean','age']]

      Age_Mean   age
0    22.000000  22.0
1    38.000000  38.0
2    26.000000  26.0
3    35.000000  35.0
4    35.000000  35.0
..         ...   ...
886  27.000000  27.0
887  19.000000  19.0
888  29.699118   NaN
889  26.000000  26.0
890  32.000000  32.0

[891 rows x 2 columns]

### --> Mean Imputation works well when we have a normally distributed data.

### --> But if we have a right or left skewed data than we replace with median.

### 2. Median Value Imputation. 

We use this if we have Outliers in the dataset.

In [8]:
df['Age_median'] = df['age'].fillna(df['age'].median())

In [9]:
df[['Age_Mean', 'age', 'Age_median']]

      Age_Mean   age  Age_median
0    22.000000  22.0        22.0
1    38.000000  38.0        38.0
2    26.000000  26.0        26.0
3    35.000000  35.0        35.0
4    35.000000  35.0        35.0
..         ...   ...         ...
886  27.000000  27.0        27.0
887  19.000000  19.0        19.0
888  29.699118   NaN        28.0
889  26.000000  26.0        26.0
890  32.000000  32.0        32.0

[891 rows x 3 columns]

### 3. Mode Imputation Technqiue

- This can be used with Categorical Values.

In [10]:
## Lets check mising values.
df[df['embarked'].isnull()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Age_Mean,Age_median
61,1,1,female,38.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True,38.0,38.0
829,1,1,female,62.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True,62.0,62.0

In [11]:
## We can see there are only two missing values, now we will see what are the entries in the 'embarked' column.
df['embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [12]:
## How to find mode:
mode_value = df[df['embarked'].notna()]['embarked'].mode()[0]

In [13]:
df['embarked_mode'] = df['embarked'].fillna(mode_value)

In [14]:
df[['embarked_mode', 'embarked']]

    embarked_mode embarked
0               S        S
1               C        C
2               S        S
3               S        S
4               S        S
..            ...      ...
886             S        S
887             S        S
888             S        S
889             C        C
890             Q        Q

[891 rows x 2 columns]

In [16]:
df[df['embark_town'].isnull()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Age_Mean,Age_median,embarked_mode
61,1,1,female,38.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True,38.0,38.0,S
829,1,1,female,62.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True,62.0,62.0,S

In [17]:
df['embark_town'].unique()

array(['Southampton', 'Cherbourg', 'Queenstown', nan], dtype=object)

In [18]:
embark_town_m = df[df['embark_town'].notna()]['embark_town'].mode()[0]

In [19]:
df['embark_town_mode'] = df['embark_town'].fillna(embark_town_m)

In [20]:
df[['embark_town','embark_town_mode']]

     embark_town embark_town_mode
0    Southampton      Southampton
1      Cherbourg        Cherbourg
2    Southampton      Southampton
3    Southampton      Southampton
4    Southampton      Southampton
..           ...              ...
886  Southampton      Southampton
887  Southampton      Southampton
888  Southampton      Southampton
889    Cherbourg        Cherbourg
890   Queenstown       Queenstown

[891 rows x 2 columns]