# Section 24.6 Target Guided Ordinal Encoding

- Its a technique used to categorical variables based on thair relationship with the target variable. 
- This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our ML model.
- In Target Guided Ordinal Encoding, we replace each categorical variable with a numerical value based on the mean or median of the target variable for that category. 
- This creates a monotonic relationship between variable and the target variable, which can improve the predictive power of our model.

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Creating a sample dataframe with categorical variable and a target variable.
df = pd.DataFrame({
    'city': ['New York','London','Paris','Tokyo','New York','Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [4]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [6]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [7]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [8]:
df['city_encoded'] = df['city'].map(mean_price)

In [9]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [10]:
df[['city','city_encoded']]

       city  city_encoded
0  New York         190.0
1    London         150.0
2     Paris         310.0
3     Tokyo         250.0
4  New York         190.0
5     Paris         310.0